### ISSUE TITLE
test by creating Suave Hello World

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/dotnet-vscode#3]
I'm hoping @enricosada can help out here. I'd like to test this docker image by running and debugging a Suave app from it, which Enrico just did:
https://twitter.com/enricosada/status/733706107911294977

**Comment by ctaggart** [comment]
I found the PR with instructions that I can test:
https://github.com/SuaveIO/suave/pull/439

**Comment by enricosada** [comment]
@ctaggart to just consume Suave , check https://github.com/SuaveIO/suave/pull/439#issuecomment-220875630 it's an hello world.

the examples/Example in pr works too, but .net plumbing ( project.json, nuget.config ) is the same

**note** it's a suave package built by myself, just for testing, not approved by suave team. Or you can build the pr branch

**Comment by ctaggart** [comment]
## What is Cool
- Suave actually runs on .NET Core!
- Ionide is indeed bundled
- .NET Core Debugger downloads

## Needs Work
- Ionide should run on .NET Core and not Mono
- Debugging doesn't work
- Language service issues, probably because of project.json
- probably need that [future F# project system](https://github.com/Microsoft/visualfsharp/issues/1193) support

## Steps

./run-mac-x11.sh
git clone https://github.com/SuaveIO/Suave-CoreCLR-sample.git
cd Suave-CoreCLR-sample
code . &
dotnet restore

# change listening IP from 127.0.0.1 to 0.0.0.0

dotnet run
http://127.0.0.1:8083/

## Code Change

``` fs
open Suave
open System.Net

[<EntryPoint>]
let main argv =
    let config =
        { defaultConfig with
            bindings = 
                [{ defaultConfig.bindings.[0] with
                    socketBinding = 
                    { 
                        ip = IPAddress.Parse "0.0.0.0"
                        port = uint16 8083
                    }
                }]
        }
    startWebServer config (Successful.OK "Hello World!")
    0
```

**Comment by ctaggart** [comment]
Video demo of this status has been uploaded to YouTube:
https://youtu.be/qjH1yaWcUHI

[![YouTube Move: Status of Suave running on .NET Core 1.0 RC2](https://cloud.githubusercontent.com/assets/80104/15492194/841160ce-212d-11e6-8416-fcc2ef350e74.png)](https://youtu.be/qjH1yaWcUHI)

Made it 640px wide and added the play button using http://www.giikers.com/iwc:
[![YouTube Move: Status of Suave running on .NET Core 1.0 RC2](https://cloud.githubusercontent.com/assets/80104/15492325/f336a2d8-212e-11e6-944b-2d240058a6a5.png)](https://youtu.be/qjH1yaWcUHI)

**Comment by Krzysztof-Cieslak** [comment]
Problem with Ionide initialization - you need to run `dotnet build` (which generates some additional files in background) before you'll get F# editor features working.

**Comment by enricosada** [comment]
also debug should work, you need to set project.json to generate portablePdb .
if doesnt, maybe we need to upgrade the fsc compiler version, i'll check soon, didnt test it with preview1

**Comment by ctaggart** [comment]
Thanks @enricosada, I'll test it out.
